config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get  'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'login'  => 'sessions#destroy'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  #railsが勝手にpostとpatchを使い分ける(謎)
  patch 'signup' => 'users#create'
  get 'puzzle' => 'puzzle#index'
  post 'puzzle' => 'puzzle#vote'
  get 'puzzle' => 'puzzle#win'
  get 'winners' => 'winners#show'
  post 'winners' => 'winners#create'
  get 'winners/new' => 'winners#new'

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, length: { maximum: 255 } ,uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead

  protect_from_forgery with: :exception

  helper :all
  helper_method :current_user
  helper_method :logged_in?

  # 渡されたユーザーでログインする
   def log_in(user)
     session[:user_id] = user.id
   end

   # ログアウト
   def log_out
    session.delete(:user_id)
    @current_user = nil
   end

   # 現在のユーザー
   def current_user
     @current_user ||= User.find_by(id: session[:user_id])
   end

   def logged_in?
      !current_user.nil?
   end

end

app/controllers/puzzle_controller.rb
class PuzzleController < ApplicationController

protect_from_forgery except: [:index, :vote]

  def index

    #ログイン判定
    if logged_in?
      @user = current_user

      #コイルが勝っていたら遷移
      if current_user.coil > current_user.pikachu
        redirect_to controller: 'winners', action: 'new'
      else
        render :action => 'index'
      end
    else
      redirect_to root_url
    end

  end

  def vote

    #投票された対象のデータベースの値をインクリメント
    if params[:target] == 'pikachu'
      flash[:success] = 'ピカチュウに投票！'
      current_user.update_attribute(:pikachu,current_user.pikachu+1)
    elsif params[:target] == 'coil'
      flash[:success] = 'コイルに投票！'
      current_user.update_attribute(:coil,current_user.coil+1)
    end

    redirect_to :action => 'index'

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to controller: 'puzzle', action: 'index'
    end
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to controller: 'puzzle', action: 'index'
    else
      flash.now[:danger] = 'Invalid name/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @winner = User.where.not(win_comment: nil).limit(10).order('win_at DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users/new
  def new
    if logged_in?
      redirect_to controller: 'puzzle', action: 'index'
    else
      @user = User.new
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.update_attribute(:created_at,Time.zone.now.to_s(:db))
      if @user.save
        log_in @user
        redirect_to controller: 'puzzle', action: 'index'
      else
        render 'new'
      end
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_user
  #     @user = User.find(params[:id])
  #   end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
    private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController

  def new
    check_user
  end

  def create
    check_user
    if !current_user.win_comment
      current_user.update_attribute(:win_comment,params[:users][:win_comment])
      current_user.update_attribute(:win_at, Time.zone.now.to_s(:db))
    end
    log_out
    redirect_to root_url
  end

  def show
    @winner = User.where.not(win_comment: nil).limit(10).order('win_at DESC').page(params[:page]).per(10)
  end

  private
  def check_user
    if !logged_in? || current_user.coil <= current_user.pikachu
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav>
      <ul>
        <li><i class="fa fa-pencil"></i><%= link_to "MyBlog",   'http://mikkabouzubrowse.hatenablog.com/' %></li>
        <li><i class="fa fa-puzzle-piece"></i><%= link_to "Puzzling a Puzzler", 'http://puzzling-a-puzzler.herokuapp.com/' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header page-header">
  <h1 class="title">
    <span class="title_tag">[投票パズルLv1]</span><span class="title_main">投票でコ●ル一位にして消防ども泣かそうぜwww</span>
  </h1>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>[投票パズルLv1]投票でコ●ル一位にして消防ども泣かそうぜwww</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%#= render 'meta/google_tag_manager' %>
  <meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1" />
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= h(flash[:debug]) %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/meta/_google_tag_manager.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KG236B"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KG236B');</script>
<!-- End Google Tag Manager -->

app/views/puzzle/index.html.erb
<div class="puzzle_index">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="jumbotron">
    <p>クリア条件：コイルの票数をピカチュウより多くする</p>
  </div>
    <fieldset>
      <legend>投票フォーム</legend>
      <%= h(flash[:success]) %>
      <form role="form" class="form-horizontal" action="/puzzle" accept-charset="UTF-8" method="post">
          <div class="form-group my-form-group">
            <div class="radio-inline target-label">
              <input type="radio" value="pikachu" checked="checked" name="target"/>
              ピカチュウ：<%= current_user.pikachu %>
            </div>
            <img src="/assets/images/pikachu.jpg" alt="Pikachu" class="target-image" />
          </div>

          <div class="form-group my-form-group">
            <div class="radio-inline target-label">
              <input type="radio" value="coil" name="target" />
              コイル：<%= current_user.coil %>
            </div>
            <img src="/assets/images/coil.jpg" alt="Pikachu" class="target-image"/>
          </div>
          <div class="form-group submit_btn">
            <input type="submit" name="commit" value="Vote" class="btn btn-primary" />
          </div>
      </form>
    </fieldset>
    <ul class="links">
      <li><%= link_to "元ネタ", "http://dic.nicovideo.jp/v/sm4205927" %></li>
      <li><%= link_to "ログアウト", login_path, method: "delete" %></li>
    </ul>
  </div>
</div>
</div>
</div>

app/views/top/index.html.erb
<div class="top_index">
  <div class="main">
    <div class="hack_link">
      <%= image_tag("/assets/images/koilaiku.png") %>
      <%= link_to "Hack!", signup_path%>
      <%= image_tag("/assets/images/pikariki.png") %>
    </div>
    <div class="winner_link">
      <a data-toggle="collapse" data-target="#winner">Winners(<%= @winner.count %>)</a>
    </div>
  </div>

  <div id="winner" class="collapse">
    <div class="accordion-inner">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>名前</th>
            <th>クリア日時</th>
            <th>コメント</th>
          </tr>
        </thead>
        <tbody>
          <% if @winner.present? %>
          <% @winner.each do |w| %>
          <tr>
            <td><%= w.name %></td>
            <td><%= w.win_at.in_time_zone('Tokyo') %></td>
            <td><%= w.win_comment%> </td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="winner_link">
        <%= link_to "All Winners(#{@winner.count})", winners_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <fieldset>
      <legend>Sign up</legend>
      <%= h(flash[:danger]) %>
      <%= bootstrap_form_for @user, :url => {:action => 'create'} , layout: :horizontal do |f|  %>
      <%= f.text_field :name %>
      <%= f.password_field :password %>
      <%= f.form_group do %>
      <%= f.submit "Sign up", class: "btn btn-primary" %>
      <% end %>
      <% end %>

      <p>return user? <%= link_to "Log in!", login_path %></p>
    </fieldset>
  </div>
</div>

app/views/winners/new.html.erb
<div class="winner_new">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="congratulation">Congratulation!</div>
      <div class="image">
        <%= image_tag("/assets/images/columbia.png") %>
      </div>
      <div class="result">
        <p>最終結果</p>
        <p>ぴかちゅう：<%= current_user.pikachu %></p>
        <p>こいる：<%= current_user.coil %></p>
      </div>
      <%= bootstrap_form_for(:users, url: '/winners', layout: :horizontal) do |f| %>
      <%= f.text_field :win_comment %>
      <%= f.form_group do %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/winners/show.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>名前</th>
      <th>クリア日時</th>
      <th>コメント</th>
    </tr>
  </thead>
  <tbody>
    <% if @winner.present? %>
    <% @winner.each do |w| %>
    <tr>
      <td><%= w.name %></td>
      <td><%= w.win_at.in_time_zone('Tokyo') %></td>
      <td><%= w.win_comment%> </td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate(@winner) %>